/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BinomialDistribution: typeof import('./src/components/experiment/distribution/BinomialDistribution.vue')['default']
    BirthdayAttack: typeof import('./src/components/experiment/chapter1/BirthdayAttack.vue')['default']
    BirthdayProblem: typeof import('./src/components/experiment/chapter1/BirthdayProblem.vue')['default']
    BuffonNeedle: typeof import('./src/components/experiment/chapter1/BuffonNeedle.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DistributionDiagram: typeof import('./src/components/experiment/distribution/DistributionDiagram.vue')['default']
    ExperimentBoard: typeof import('./src/components/experiment/ExperimentBoard.vue')['default']
    ExponentialDiagram: typeof import('./src/components/experiment/distribution/ExponentialDiagram.vue')['default']
    ExponentialDistribution: typeof import('./src/components/experiment/distribution/ExponentialDistribution.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Geometric1: typeof import('./src/components/experiment/distribution/Geometric1.vue')['default']
    Geometric2: typeof import('./src/components/experiment/distribution/Geometric2.vue')['default']
    Geometric3: typeof import('./src/components/experiment/distribution/Geometric3.vue')['default']
    GeometricBoard: typeof import('./src/components/experiment/distribution/GeometricBoard.vue')['default']
    GeometricDistribution: typeof import('./src/components/experiment/distribution/GeometricDistribution.vue')['default']
    GeometricDistribution1: typeof import('./src/components/experiment/distribution/GeometricDistribution1.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NormalDistribution: typeof import('./src/components/experiment/distribution/NormalDistribution.vue')['default']
    PoissonDistribution: typeof import('./src/components/experiment/distribution/PoissonDistribution.vue')['default']
    PositiveTest: typeof import('./src/components/experiment/chapter1/PositiveTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Slider: typeof import('primevue/slider')['default']
    ThreeDoors: typeof import('./src/components/experiment/chapter1/ThreeDoors.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UniformDiagram: typeof import('./src/components/experiment/distribution/UniformDiagram.vue')['default']
    UniformDistribution: typeof import('./src/components/experiment/distribution/UniformDistribution.vue')['default']
  }
}
